-- MySQL Script generated by MySQL Workbench
-- Tue Oct 25 21:14:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema laravel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laravel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laravel` DEFAULT CHARACTER SET utf8 ;
USE `laravel` ;

-- -----------------------------------------------------
-- Table `laravel`.`Mesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel`.`Mesto` ;

CREATE TABLE IF NOT EXISTS `laravel`.`Mesto` (
  `idMesto` INT NOT NULL AUTO_INCREMENT,
  `Nazov` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`Firma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel`.`Firma` ;

CREATE TABLE IF NOT EXISTS `laravel`.`Firma` (
  `idFirma` INT NOT NULL AUTO_INCREMENT,
  `Názov_firmy` VARCHAR(45) NOT NULL,
  `Skratka` VARCHAR(45) NOT NULL,
  `Adresa` VARCHAR(45) NOT NULL,
  `Mesto_idMesto` INT NOT NULL,
  PRIMARY KEY (`idFirma`),
  INDEX `fk_Firma_Mesto1_idx` (`Mesto_idMesto` ASC),
  CONSTRAINT `fk_Firma_Mesto1`
    FOREIGN KEY (`Mesto_idMesto`)
    REFERENCES `laravel`.`Mesto` (`idMesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`Pouzivatel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel`.`Pouzivatel` ;

CREATE TABLE IF NOT EXISTS `laravel`.`Pouzivatel` (
  `idPouzivatel` INT NOT NULL AUTO_INCREMENT,
  `Meno` VARCHAR(45) NOT NULL,
  `Priezvisko` VARCHAR(45) NOT NULL,
  `Cislo` VARCHAR(45) NOT NULL,
  `Mail` VARCHAR(45) NOT NULL,
  `Rola_pouzivatela` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPouzivatel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`Predmety`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel`.`Predmety` ;

CREATE TABLE IF NOT EXISTS `laravel`.`Predmety` (
  `idPredmety` INT NOT NULL AUTO_INCREMENT,
  `Nazov` VARCHAR(45) NOT NULL,
  `Skratka` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPredmety`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`Studijny_program`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel`.`Studijny_program` ;

CREATE TABLE IF NOT EXISTS `laravel`.`Studijny_program` (
  `idStudijny_program` INT NOT NULL AUTO_INCREMENT,
  `Nazov` VARCHAR(45) NOT NULL,
  `Skratka` VARCHAR(45) NOT NULL,
  `Predmety_idPredmety` INT NOT NULL,
  PRIMARY KEY (`idStudijny_program`),
  INDEX `fk_Studijny_program_Predmety1_idx` (`Predmety_idPredmety` ASC),
  CONSTRAINT `fk_Studijny_program_Predmety1`
    FOREIGN KEY (`Predmety_idPredmety`)
    REFERENCES `laravel`.`Predmety` (`idPredmety`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`Prax`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel`.`Prax` ;

CREATE TABLE IF NOT EXISTS `laravel`.`Prax` (
  `idPrax` INT NOT NULL AUTO_INCREMENT,
  `Info_o_praxi` VARCHAR(100) NOT NULL,
  `Student_idPouzivatel` INT NULL,
  `Datum_start` DATE NULL,
  `Datum_end` DATE NULL,
  `Firma_idFirma` INT NOT NULL,
  `Kontaktna_osoba_idPouzivatel` INT NOT NULL,
  `Aktuálny_stav` VARCHAR(45) NOT NULL,
  `Report` VARCHAR(100) NULL,
  `Spatna_vazba_k_praxi_studenta` VARCHAR(100) NULL,
  `Studijny_program_idStudijny_program` INT NOT NULL,
  `Pracovnik_FPVaI_idPouzivatel1` INT NOT NULL,
  PRIMARY KEY (`idPrax`),
  INDEX `fk_Prax_Firma1_idx` (`Firma_idFirma` ASC),
  INDEX `fk_Prax_Pouzivatel1_idx` (`Student_idPouzivatel` ASC),
  INDEX `fk_Prax_Studijny_program1_idx` (`Studijny_program_idStudijny_program` ASC),
  INDEX `fk_Prax_Pouzivatel2_idx` (`Kontaktna_osoba_idPouzivatel` ASC),
  INDEX `fk_Prax_Pouzivatel3_idx` (`Pracovnik_FPVaI_idPouzivatel1` ASC),
  CONSTRAINT `fk_Prax_Firma1`
    FOREIGN KEY (`Firma_idFirma`)
    REFERENCES `laravel`.`Firma` (`idFirma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prax_Pouzivatel1`
    FOREIGN KEY (`Student_idPouzivatel`)
    REFERENCES `laravel`.`Pouzivatel` (`idPouzivatel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prax_Studijny_program1`
    FOREIGN KEY (`Studijny_program_idStudijny_program`)
    REFERENCES `laravel`.`Studijny_program` (`idStudijny_program`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prax_Pouzivatel2`
    FOREIGN KEY (`Kontaktna_osoba_idPouzivatel`)
    REFERENCES `laravel`.`Pouzivatel` (`idPouzivatel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prax_Pouzivatel3`
    FOREIGN KEY (`Pracovnik_FPVaI_idPouzivatel1`)
    REFERENCES `laravel`.`Pouzivatel` (`idPouzivatel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`Typ_zmluvy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel`.`Typ_zmluvy` ;

CREATE TABLE IF NOT EXISTS `laravel`.`Typ_zmluvy` (
  `idTyp_zmluvy` INT NOT NULL AUTO_INCREMENT,
  `Typ` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTyp_zmluvy`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`Firma_has_Pouzivatel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel`.`Firma_has_Pouzivatel` ;

CREATE TABLE IF NOT EXISTS `laravel`.`Firma_has_Pouzivatel` (
  `Firma_idFirma` INT NOT NULL,
  `Student_idPouzivatel` INT NOT NULL,
  `Typ_zmluvy_idTyp_zmluvy` INT NOT NULL,
  PRIMARY KEY (`Firma_idFirma`, `Student_idPouzivatel`),
  INDEX `fk_Firma_has_Pouzivatel_Pouzivatel1_idx` (`Student_idPouzivatel` ASC),
  INDEX `fk_Firma_has_Pouzivatel_Firma1_idx` (`Firma_idFirma` ASC),
  INDEX `fk_Firma_has_Pouzivatel_Typ_zmluvy1_idx` (`Typ_zmluvy_idTyp_zmluvy` ASC),
  CONSTRAINT `fk_Firma_has_Pouzivatel_Firma1`
    FOREIGN KEY (`Firma_idFirma`)
    REFERENCES `laravel`.`Firma` (`idFirma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Firma_has_Pouzivatel_Pouzivatel1`
    FOREIGN KEY (`Student_idPouzivatel`)
    REFERENCES `laravel`.`Pouzivatel` (`idPouzivatel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Firma_has_Pouzivatel_Typ_zmluvy1`
    FOREIGN KEY (`Typ_zmluvy_idTyp_zmluvy`)
    REFERENCES `laravel`.`Typ_zmluvy` (`idTyp_zmluvy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
